name: Ubuntu self build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: git submodules
      run: git submodule update --init
    - name: install stuff
      run: sudo apt update && sudo apt-get install g++-10
    - name: build
      run: ./build-linux.sh g++10
      shell: bash
    - name: self build
      run: build/matmake2 -t gcc

