name: Ubuntu self build (gcc)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: git submodules
      run: git submodule update --init
    - name: build
      run: ./build-linux.sh
      shell: bash
    - name: self build
      run: build/matmake2 -t gcc

