name: Ubuntu Cmake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: git submodules
      run: git submodule update --init
    - name: install stuff
      run: sudo apt update && sudo apt-get install ninja-build g++-10
    - name: install stuff
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh &&  sudo ./llvm.sh 11
    - name: create build dir
      run: mkdir build
    - name: cmake
      working-directory: build
      run: cmake .. -G Ninja
      shell: bash
      env:
        CXX: g++-10
    - name: ninja
      working-directory: build
      run: ninja
    - name: test
      run: ctest --verbose
      working-directory: build

    - name: create example project
      run: build/matmake2 --init test
    - name: build example project
      run: build/matmake2 -C test --target gcc

