name: Ubuntu self build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: git submodules
      run: git submodule update --init
    - name: install stuff
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh &&  sudo ./llvm.sh 10
    - name: build
      run: ./build-linux.sh clang++-10
      shell: bash
    - name: self build
      run: build/matmake2 -t clang

