name: Ubuntu self build (clang)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: git submodules
      run: git submodule update --init
    - name: install stuff
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh &&  sudo ./llvm.sh 11
    - name: build
      run: ./build-linux.sh clang++-11
      shell: bash
    - name: self build
      run: build/matmake2 -t clang
    - name: test
      run: build/matmake2 -t clang
    - name: create example project
      run: build/clang/matmake2 --init test
    - name: build example project
      run: build/clang/matmake2 -C test --target clang
    - name: Build demo project1
      run: build/clang/matmake2 -C build/clang/demos/project1 --target clang
    - name: Build demo staticlib
      run: build/clang/matmake2 -C build/clang/demos/staticlib --target clang
    - name: Build demo dynamiclib
      run: build/clang/matmake2 -C build/clang/demos/dynamiclib --target clang
    - name: Build demo module project
      run: build/clang/matmake2 -C build/clang/demos/modules --target clang

